export { default as Home } from './Home'
export { default as NotFound } from './NotFound'
export { default as Error } from './Error'
export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as CustomerList } from './CustomerList'
export { default as AddBird } from './ManageBird/AddBird'
export { default as BirdList } from './ManageBird/BirdList'
